server:
  session-timeout: 1800
security:
basic:
               enabled: false
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes:  47.105.64.46:9300
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
