server:
  session-timeout: 1800
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
index:
  productCout: 100